// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Word struct {
	ID       int32
	Word     string
	Type     string
	Meaning  string
	Sentence string
	Origin   string
}

type WordConfusion struct {
	WordID         int32
	ConfusedWithID int32
}
