// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: words.sql

package database

import (
	"context"
	"database/sql"
)

const getRandomWord = `-- name: GetRandomWord :one
SELECT id, word, type, meaning, sentence FROM words ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomWord(ctx context.Context) (Word, error) {
	row := q.db.QueryRowContext(ctx, getRandomWord)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Type,
		&i.Meaning,
		&i.Sentence,
	)
	return i, err
}

const getWordByID = `-- name: GetWordByID :one
SELECT id, word, type, meaning, sentence FROM words WHERE id = $1
`

func (q *Queries) GetWordByID(ctx context.Context, id int32) (Word, error) {
	row := q.db.QueryRowContext(ctx, getWordByID, id)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Type,
		&i.Meaning,
		&i.Sentence,
	)
	return i, err
}

const getWordConfusions = `-- name: GetWordConfusions :many
SELECT w.id, w.word, w.type, w.meaning, w.sentence FROM words w
JOIN word_confusions wc ON w.id = wc.confused_with_id
WHERE wc.word_id = $1
ORDER BY w.word
`

func (q *Queries) GetWordConfusions(ctx context.Context, wordID int32) ([]Word, error) {
	rows, err := q.db.QueryContext(ctx, getWordConfusions, wordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Type,
			&i.Meaning,
			&i.Sentence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWords = `-- name: SearchWords :many
SELECT id, word, type, meaning, sentence FROM words WHERE word ILIKE '%' || $1 || '%' ORDER BY word
`

func (q *Queries) SearchWords(ctx context.Context, dollar_1 sql.NullString) ([]Word, error) {
	rows, err := q.db.QueryContext(ctx, searchWords, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Type,
			&i.Meaning,
			&i.Sentence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
