// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: words.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createWord = `-- name: CreateWord :one
INSERT INTO words (word, type, meaning, sentence, origin, confused_with)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, word, type, meaning, sentence, origin, confused_with
`

type CreateWordParams struct {
	Word         string
	Type         string
	Meaning      string
	Sentence     string
	Origin       string
	ConfusedWith []string
}

func (q *Queries) CreateWord(ctx context.Context, arg CreateWordParams) (Word, error) {
	row := q.db.QueryRowContext(ctx, createWord,
		arg.Word,
		arg.Type,
		arg.Meaning,
		arg.Sentence,
		arg.Origin,
		pq.Array(arg.ConfusedWith),
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Type,
		&i.Meaning,
		&i.Sentence,
		&i.Origin,
		pq.Array(&i.ConfusedWith),
	)
	return i, err
}

const getRandomWord = `-- name: GetRandomWord :one
SELECT id, word, type, meaning, sentence, origin, confused_with FROM words ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomWord(ctx context.Context) (Word, error) {
	row := q.db.QueryRowContext(ctx, getRandomWord)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Type,
		&i.Meaning,
		&i.Sentence,
		&i.Origin,
		pq.Array(&i.ConfusedWith),
	)
	return i, err
}

const getWordByID = `-- name: GetWordByID :one
SELECT id, word, type, meaning, sentence, origin, confused_with FROM words WHERE id = $1
`

func (q *Queries) GetWordByID(ctx context.Context, id int32) (Word, error) {
	row := q.db.QueryRowContext(ctx, getWordByID, id)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Type,
		&i.Meaning,
		&i.Sentence,
		&i.Origin,
		pq.Array(&i.ConfusedWith),
	)
	return i, err
}

const searchWords = `-- name: SearchWords :many
SELECT id, word, type, meaning, sentence, origin, confused_with FROM words WHERE word ILIKE '%' || $1 || '%' ORDER BY word
`

func (q *Queries) SearchWords(ctx context.Context, dollar_1 sql.NullString) ([]Word, error) {
	rows, err := q.db.QueryContext(ctx, searchWords, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Type,
			&i.Meaning,
			&i.Sentence,
			&i.Origin,
			pq.Array(&i.ConfusedWith),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWord = `-- name: UpdateWord :one
UPDATE words
SET word = $2,
    type = $3,
    meaning = $4,
    sentence = $5,
    origin = $6,
    confused_with = $7
WHERE id = $1
RETURNING id, word, type, meaning, sentence, origin, confused_with
`

type UpdateWordParams struct {
	ID           int32
	Word         string
	Type         string
	Meaning      string
	Sentence     string
	Origin       string
	ConfusedWith []string
}

func (q *Queries) UpdateWord(ctx context.Context, arg UpdateWordParams) (Word, error) {
	row := q.db.QueryRowContext(ctx, updateWord,
		arg.ID,
		arg.Word,
		arg.Type,
		arg.Meaning,
		arg.Sentence,
		arg.Origin,
		pq.Array(arg.ConfusedWith),
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Type,
		&i.Meaning,
		&i.Sentence,
		&i.Origin,
		pq.Array(&i.ConfusedWith),
	)
	return i, err
}
